#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<EOF
Usage: $0 [version]

Creates a GitHub Release for the given version (tag). If version is omitted the latest tag is used.
Options:
  --draft        Create the release as a draft (do not publish)
  --prerelease   Mark the release as a prerelease
  --overwrite    If a release for the tag exists, delete and recreate it
  --notes-file F Use notes from a file instead of CHANGELOG.md or git log
  --help         Show this help

Examples:
  $0 v1.2.3        # create/publish release for tag v1.2.3
  $0 1.2.3 --draft  # create release as draft for v1.2.3
  $0               # use latest tag
EOF
  exit 1
}

if ! command -v gh >/dev/null 2>&1; then
  echo "Error: GitHub CLI 'gh' is required. Install it and authenticate (gh auth login or set GH_TOKEN)." >&2
  exit 2
fi

VERSION_ARG=""
DRAFT=false
PRERELEASE=false
OVERWRITE=false
NOTES_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --draft) DRAFT=true; shift ;;
    --prerelease) PRERELEASE=true; shift ;;
    --overwrite) OVERWRITE=true; shift ;;
    --notes-file) NOTES_FILE="$2"; shift 2 ;;
    -h|--help) usage ;;
    --) shift; break ;;
    -*) echo "Unknown option: $1" >&2; usage ;;
    *) VERSION_ARG="$1"; shift ;;
  esac
done

# Determine tag
TAG=""
if [[ -n "$VERSION_ARG" ]]; then
  TAG="$VERSION_ARG"
  # Ensure leading 'v' for tag
  if [[ "$TAG" != v* ]]; then
    TAG="v$TAG"
  fi
else
  TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
  if [[ -z "$TAG" ]]; then
    echo "No tags found in repository and no version provided." >&2
    exit 3
  fi
fi

VERSION_NO_V="${TAG#v}"

echo "Preparing GitHub release for tag: $TAG"

# Helper: extract notes from CHANGELOG.md
extract_notes_from_changelog() {
  local ver="$1"
  if [[ -f CHANGELOG.md ]] && grep -q "^## \[${ver}\]" CHANGELOG.md; then
    awk "/^## \[${ver}\]/ {flag=1; next} /^## \[/ { if(flag) exit } flag{ print }" CHANGELOG.md | sed '/^$/d'
  else
    return 1
  fi
}

# Helper: build notes from git log
build_notes_from_git() {
  local tag="$1"
  # find previous tag
  PREV_TAG=$(git tag --sort=-v:refname | grep -v "^${tag}$" | head -n1 || true)
  if [[ -n "$PREV_TAG" ]]; then
    git log --no-merges --pretty=format:'- %s (%an)' "${PREV_TAG}".."${tag}"
  else
    # fallback: last 50 commits up to the tag
    git log --no-merges --pretty=format:'- %s (%an)' "${tag}" -n 50
  fi
}

NOTES_CONTENT=""
if [[ -n "$NOTES_FILE" ]]; then
  if [[ ! -f "$NOTES_FILE" ]]; then
    echo "Notes file $NOTES_FILE not found." >&2
    exit 4
  fi
  NOTES_CONTENT=$(cat "$NOTES_FILE")
else
  if NOTES_CONTENT=$(extract_notes_from_changelog "$VERSION_NO_V"); then
    : # got notes from changelog
  else
    NOTES_CONTENT=$(build_notes_from_git "$TAG")
  fi
fi

if [[ -z "$NOTES_CONTENT" ]]; then
  NOTES_CONTENT="No changelog entry found for ${VERSION_NO_V}. See commit history for details."
fi

# Compose final notes
NOTES_FILE_TMP=$(mktemp)
cat > "$NOTES_FILE_TMP" <<EOF
## Release ${TAG}

${NOTES_CONTENT}

---
Generated by scripts/create-gh-release.sh
EOF

# Delete existing release if requested and exists
if gh release view "$TAG" >/dev/null 2>&1; then
  if [[ "$OVERWRITE" == true ]]; then
    echo "Existing release found for $TAG — deleting (overwrite enabled)"
    gh release delete "$TAG" --yes
  else
    echo "Release $TAG already exists. Use --overwrite to replace it or choose a different tag." >&2
    rm -f "$NOTES_FILE_TMP"
    exit 5
  fi
fi

# Build gh command
GH_CMD=(gh release create "$TAG" --title "$TAG" --notes-file "$NOTES_FILE_TMP")
if [[ "$DRAFT" == true ]]; then
  GH_CMD+=(--draft)
fi
if [[ "$PRERELEASE" == true ]]; then
  GH_CMD+=(--prerelease)
fi

# Execute
echo "Running: ${GH_CMD[*]}"
"${GH_CMD[@]}"
EXIT_CODE=$?

rm -f "$NOTES_FILE_TMP"

if [[ $EXIT_CODE -ne 0 ]]; then
  echo "gh release create failed with code $EXIT_CODE" >&2
  exit $EXIT_CODE
fi

echo "Release $TAG created successfully."
exit 0
